# Generated by Django 3.2.25 on 2024-06-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240601_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barber',
            old_name='social_url',
            new_name='facebook_url',
        ),
        migrations.AddField(
            model_name='barber',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
