# Generated by Django 3.2.25 on 2024-06-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20240601_0749'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
