# Generated by Django 3.2.25 on 2024-06-01 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20240601_0856'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
